### ISSUE TITLE
SPI Timing issue

### ISSUE THREAD

**Issue by punkkeks** [andysworkshop/stm32plus#103]
The following code produces the following signal trace.

    Spi1<>::Parameters params;
    params.spi_direction = SPI_Direction_1Line_Tx;
    params.spi_mode = SPI_Mode_Master;
    Spi1<> spi(params);

    spi.setNss(false);
    spi.send(initCode, 14); //14 bytes for LCD initialisation
    spi.setNss(true);

![snapshot4](https://cloud.githubusercontent.com/assets/921462/6846993/235fdad4-d3c3-11e4-818c-69fdddb78def.png)

As you might see, the enable pin (5) is going high to early (round about 0.22ms)

Netherless if the spi.setNss is correct way to do it or not, this is a problem. I think we don't wait for the last byte to be sent. Maybe we want to fix that!

**Comment by andysworkshop** [comment]
Yes you're right. I'll need to add a method to poll the `BSY` bit in `SPI_SR` and update the examples accordingly.

**Comment by andysworkshop** [comment]
Fixed with new `waitForIdle()` method. Tested on F0/F1/F4.
