### ISSUE TITLE
Weird ripple when using Timer with GpioFeature

### ISSUE THREAD

**Issue by punkkeks** [andysworkshop/stm32plus#104]
The following code produces the following output. This can lead to strange behavoir (in my example adafruit led strip)

```
int main()
{
    Timer1<Timer1GpioFeature<TIMER_REMAP_NONE,TIM1_CH1_OUT>> timer;

    while(1) {}
    return 0;
}
```

![snapshot6](https://cloud.githubusercontent.com/assets/921462/6871432/ce5a2efa-d4a2-11e4-9a74-b0431dd0297b.png)
Don't know where it comes from or why this happens, but it should be fixed ;)

**Comment by andysworkshop** [comment]
No progress so closing.
