### ISSUE TITLE
TcpTextLineReceiver - Feature request

### ISSUE THREAD

**Issue by danielschramm** [andysworkshop/stm32plus#120]
Hello,

currently the TcpTextLineReceiver only detects \n as end of line.
It would be a helpfull feature to define own stop sequences. 
In my specific case "\r\n" is needed since I use msgpack for sending data which itself uses "\n" in it's encoding.
Other application might have other Command end definitions.

Thanks,

Daniel

**Comment by andysworkshop** [comment]
No progress so closing, PR welcomed if the feature is needed.
