### ISSUE TITLE
Iterate over all enabled pins

### ISSUE THREAD

**Issue by punkkeks** [andysworkshop/stm32plus#133]
When I have a gpio bank set, e.g.

    GpioD<DefaultDigitalOutputFeature<1, 3, 5, 6, 7, 10, 14>> gd;

and I want to iterate over all pins (1, 3, 5, 6, 7, 10, 14) there is no comfortable way to do it.
I would suggest to add begin/end and cbegin/cend methods with the type of `Iterator<Gpio>`

**Comment by andysworkshop** [comment]
Completed and there's a [forum post](http://andybrown.me.uk/forum/index.php/topic,67.msg488.html?PHPSESSID=kp3olcsfiqac2mmcr2ittoq975#msg488) with some examples.

**Comment by punkkeks** [comment]
Awesome :) I love it! Thanks a lot for this feature
