### ISSUE TITLE
CAN support

### ISSUE THREAD

**Issue by andysworkshop** [andysworkshop/stm32plus#139]
CAN is a major peripheral on the STM32 family and we don't yet support it in stm32plus.

**Comment by andysworkshop** [comment]
@Elektroman2 I've reviewed your pull request and have commited it to a new branch `can-support`. Can you verify that it still works for you?

Also, are you planning to commit a simple CAN bus example?

**Comment by Elektroman2** [comment]
I found it, I will send everything tomorrow. ( I messed up things with git :( )

**Comment by andysworkshop** [comment]
thanks to @spiralray we've now got F4 support and I'm about ready to merge `can-support` to `master` unless anyone's got any objections...

**Comment by andysworkshop** [comment]
`can-support` is now merged to `master`. F0 support will complete this feature but I'll close this issue now and track F0 support under a new issue.
