### ISSUE TITLE
Should builds use newlib-nano?

### ISSUE THREAD

**Issue by dholth** [andysworkshop/stm32plus#163]
I noticed newlib-nano uses a lot less RAM.

**Comment by andysworkshop** [comment]
Yes, I've used it myself with a project that used stm32plus (see [here](https://github.com/andysworkshop/awcopper/blob/master/stm32/SConstruct#L71)). No issues found by me in my limited use case.

**Comment by dholth** [comment]
Thanks, saved about 2k of RAM.
