### ISSUE TITLE
(question) Where does the build output (.a files, headers) get compiled to?

### ISSUE THREAD

**Issue by twitchyliquid64** [andysworkshop/stm32plus#178]
Where does the build output (.a files, headers) get compiled to, if you DO NOT select the install??

I am currently automating the build and was liek welp when I couldnt find them after it built successfully.

**Comment by andysworkshop** [comment]
Headers are not installed unless you install, they remain in place.

The library `.a` file is installed in a subdirectory of `lib/build`. The subdirectory name is generated from your `scons` build parameters.

Similarly, the examples each have a `build` subdirectory set up the same way.
