### ISSUE TITLE
About the use of MillisecondTimer for timeout

### ISSUE THREAD

**Issue by tokoro10g** [andysworkshop/stm32plus#19]
Hi, I have a suggestion for the implementation of timeout.

Your code seem to have implemented it by using `MillisecondTimer`, but this fact is not well-documented.

I think that `MillisecondTimer` and the timeout functionality should be separated.
It is not trivial that timeout is automatically enabled when using `MillisecondTimer` so they should be switched like this:

(When using timeout)

``` c++
I2C1_Default<I2CTimeoutFeature,...> i2c; // Add timeout feature which initialises MillisecondTimer automatically
// MillisecondTimer::initialise(); // Now this isn't necessary because of the timeout feature
```

(When using `MillisecondTimer` with no timeout)

``` c++
I2C1_Default<SomeOtherFeature,...> i2c; // Doesn't use MillisecondTimer for timeout
MillisecondTimer::initialise(); // Necessary to use MillisecondTimer
```

Thank you for your fascinating library and I hopefully make it more efficient and useful.

**Comment by mikepurvis** [comment]
Waking this thread up again. Sorry I was kind of lukewarm on the `MillisecondTimerHolder` idea at the time, but having `delay` be a swappable affair would also be really valuable, for the case where you want to yield your RTOS thread when blocking on a peripheral.
