### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by xhybb** [andysworkshop/stm32plus#193]
BigEndianCrc.h:31:33: error: invalid conversion from 'int' to 'stm32plus::Endian' [-fpermissive]

GNU ARM Embedded Toolchain version is 5-2016-q3-update

**Comment by punkkeks** [comment]
To solve this issue for the moment just remove all occurrings of -Werror in the SConstruct. 
To

**Comment by tokoro10g** [comment]
Hi, I also ran into this issue with GCC 5.4.1 (https://launchpad.net/gcc-arm-embedded/5.0/5-2016-q2-update).

The problem was that `LITTLE_ENDIAN` and `BIG_ENDIAN` were defined by macros in machine/endian.h in libc.
I have no idea how to fix this, but just FYI.

**Comment by andysworkshop** [comment]
Macros should never have been invented.
