### ISSUE TITLE
eclipse kepler

### ISSUE THREAD

**Issue by mado1362** [andysworkshop/stm32plus#204]
I  install kepler new.but plug-in gnu arm on eclipse kepler not installed

**Comment by mado1362** [comment]
the new plug-ins cannot be installed on older Eclipses; for this, use the latest 3.x version, available from the deprecated update site (http://gnuarmeclipse.sourceforge.net/updates);

**Comment by hariudkmr** [comment]
I had recently faced similar issue. The new gnu arm plugin is supported for eclipse neon version and above. can directly download the eclipse cdt from this location which has gnu-arm plugin pre-installed.
https://github.com/gnu-mcu-eclipse/org.eclipse.epp.packages/releases/
