### ISSUE TITLE
Support the USB peripheral on the F4

### ISSUE THREAD

**Issue by andysworkshop** [andysworkshop/stm32plus#34]
The next major peripheral to be supported will be USB (high speed) on the F4. I plan to incrementally release support for peripheral and host modes and the popular device classes. Updates will be posted to this issue when I start work on support for this complex peripheral.

**Comment by andysworkshop** [comment]
The `usb` branch is now fully merged to `master` and `usb` has been deleted. Please use `master` for further testing.

There's no going back now :)

**Comment by zakamik** [comment]
Hello,
any chance for f1 support?

Thanks

**Comment by andysworkshop** [comment]
@zakamik When the F4 support is bedded in then I'll look at back-porting down to the F1 and the F0.

**Comment by zakamik** [comment]
That would be really great.
Thanks for you library, very useful piece of software

**Comment by jtewell** [comment]
Is it possible to make composite USB devices, say CDC and HID?

**Comment by andysworkshop** [comment]
Yes it's possible, though not supported by this library.
