### ISSUE TITLE
Verification for CircularBufferInputOutputStream

### ISSUE THREAD

**Issue by mikepurvis** [andysworkshop/stm32plus#96]
Looks like there aren't any examples or tests for this class. My use (writing one character at a time from an ISR, reading one character at a time from the main loop, checking `available()`) is finding that the buffer fills up, with both the read and write pointers pointing at the same point midway through the buffer, and neither reads nor writes succeed.

Investigation ongoing.

---

I don't really understand what `_wrappedWrite` is all about— it starts out false in the constructor, then gets set to true in the write methods, but then nothing ever clears it and once set, it blocks further writes in this logic:

```
    if(_readPtr == _writePtr && _wrappedWrite)
      return errorProvider.set(ErrorProvider::ERROR_PROVIDER_BUFFERED_IOSTREAM,E_BUFFER_FULL);
```

---

Patching in a function which periodically clears `_wrappedWrite` keeps things moving along, but it's a definite hack. Would like to figure out what the actual intent of that flag is and put in the correct solution.

**Comment by andysworkshop** [comment]
Hi Mike, can you use `memory/circular_buffer<T>` as an alternative? It's designed for your exact use case and I use it for that purpose in [this project](https://github.com/andysworkshop/awcopper).

I'll revist `CircularBufferInputOutputStream` and re-implement it so that it uses circular_buffer<T> underneath.

**Comment by mikepurvis** [comment]
I looked briefly at that, but it didn't seem suitable for conveying data from an ISR, as the read and write pointers and the buffer are not volatile.

**Comment by andysworkshop** [comment]
The data members don't need to be marked as `volatile` because all the accessor methods are `volatile`. It's a little unconventional I know but it has the desired effect and I've verified the assembly language output to ensure it's correct.

**Comment by mikepurvis** [comment]
Interesting, okay. Will switch over when able.
